### Numpy 
##### Numpy is  a linear Algebra Library in Python and it is the holy grail and the main build block of Data Science using Python. Almost all the libraries in the PyData Ecosysem Numpy as one of their main building blocks.
###### It is bound to several C libraries which makes NumPy one of the fastest libraries in python. We will learn the basics of NumPy, to get started we need to install it!

In [8]:
!pip install numpy
conda install numpy

SyntaxError: invalid syntax (1189899550.py, line 2)

In [11]:
import numpy as np

#### NumPy Arrays 
##### Numpy arrays essentially of two types: vectors and matrices. Vectors are stricky 1-D and matrices are 2-D (Note: A matrix can still have only one row or one column).


#### Creating NumPy Arrays
#### From a Python List

In [15]:
import numpy as np

In [17]:
arr1 = np.array([]) # create an empty array
arr1

array([], dtype=float64)

In [19]:
print(type(arr1))

<class 'numpy.ndarray'>


In [21]:
my_list = [1,2,3,4,5]
print(my_list)
print(type(my_list))

[1, 2, 3, 4, 5]
<class 'list'>


In [23]:
a = np.array(my_list)

In [25]:
a

array([1, 2, 3, 4, 5])

In [27]:
type(a) # nd array is number dimension array

numpy.ndarray

In [29]:
a.ndim # number of dimensions in the array

1

In [31]:
a.size # size of an array is the no. of items

5

In [33]:
a.shape # shape of array

(5,)

### Array can be of n dimensions. 

In [36]:
my_matrix = [[1,2,3,4],[5,6,7,8],[9,10,11,12]] # list of lists
my_matrix

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [38]:
import numpy as np
b = np.array(my_matrix) # generates a 2-d array
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [40]:
# array summary
print('The dimension of array', b.ndim) # dimensions of given array

The dimension of array 2


In [42]:
print('The size of array:',b.size) # number of elements in array

The size of array: 12


In [44]:
print('the datatype of elements:', b.dtype) # datatype of elements in array

the datatype of elements: int32


In [46]:
print('The type of structure:',type(b))

The type of structure: <class 'numpy.ndarray'>


In [48]:
print('The shape:',b.shape)

The shape: (3, 4)


In [50]:
b.shape

(3, 4)

In [52]:
import numpy as np

In [56]:
arr1 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [58]:
arr1.shape

(2, 2, 3)

In [60]:
arr1.ndim

3

In [62]:
arr1.size

12

### Built-in Method
#### There are lots of built-in ways to generate Arrays
### Reshape function

In [65]:
arr1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [67]:
arr1.shape

(2, 2, 3)

In [69]:
arr2=arr1.reshape((1,3,4)) # reshape function takes the new shape as its arguments

In [71]:
arr2.shape

(1, 3, 4)

In [73]:
arr2

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [75]:
arr2=arr1.reshape((3,4))

In [77]:
arr2.ndim

2

### Arange
#### Return evenly spaced values withing a given interval

In [80]:
# np.arange(start,end-1,step)

In [82]:
np.arange(15) # end; default start at 0

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [90]:
np.arange(100,0,-1) # start, end and step

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,
         9,   8,   7,   6,   5,   4,   3,   2,   1])

In [94]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### Zeros and Ones 
#### Generates arrays of zeros or ones

In [97]:
import numpy as np

In [99]:
np.zeros(3) # generates array in 1 dimension with all elements 0

array([0., 0., 0.])

In [101]:
np.zeros((5,5)) # Generates array in 2 dimensions with all elements 0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [103]:
np.ones(3) # Generates array of 1 dimension where all elements are 1

array([1., 1., 1.])

In [105]:
np.ones((4,5)) # Generates array of dimensions where all elements are 1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [107]:
np.ones((4,5,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

## Linspace 
### Return evenly spaced numbers over a specifies interval.

In [112]:
import numpy as np

In [114]:
np.linspace(1,15) # default 50 observations
# both the start adn end are included in the array

array([ 1.        ,  1.28571429,  1.57142857,  1.85714286,  2.14285714,
        2.42857143,  2.71428571,  3.        ,  3.28571429,  3.57142857,
        3.85714286,  4.14285714,  4.42857143,  4.71428571,  5.        ,
        5.28571429,  5.57142857,  5.85714286,  6.14285714,  6.42857143,
        6.71428571,  7.        ,  7.28571429,  7.57142857,  7.85714286,
        8.14285714,  8.42857143,  8.71428571,  9.        ,  9.28571429,
        9.57142857,  9.85714286, 10.14285714, 10.42857143, 10.71428571,
       11.        , 11.28571429, 11.57142857, 11.85714286, 12.14285714,
       12.42857143, 12.71428571, 13.        , 13.28571429, 13.57142857,
       13.85714286, 14.14285714, 14.42857143, 14.71428571, 15.        ])

In [116]:
np.linspace(5,25,100) # equally spaced 1 values

array([ 5.        ,  5.2020202 ,  5.4040404 ,  5.60606061,  5.80808081,
        6.01010101,  6.21212121,  6.41414141,  6.61616162,  6.81818182,
        7.02020202,  7.22222222,  7.42424242,  7.62626263,  7.82828283,
        8.03030303,  8.23232323,  8.43434343,  8.63636364,  8.83838384,
        9.04040404,  9.24242424,  9.44444444,  9.64646465,  9.84848485,
       10.05050505, 10.25252525, 10.45454545, 10.65656566, 10.85858586,
       11.06060606, 11.26262626, 11.46464646, 11.66666667, 11.86868687,
       12.07070707, 12.27272727, 12.47474747, 12.67676768, 12.87878788,
       13.08080808, 13.28282828, 13.48484848, 13.68686869, 13.88888889,
       14.09090909, 14.29292929, 14.49494949, 14.6969697 , 14.8989899 ,
       15.1010101 , 15.3030303 , 15.50505051, 15.70707071, 15.90909091,
       16.11111111, 16.31313131, 16.51515152, 16.71717172, 16.91919192,
       17.12121212, 17.32323232, 17.52525253, 17.72727273, 17.92929293,
       18.13131313, 18.33333333, 18.53535354, 18.73737374, 18.93

In [118]:
np.linspace(0,25, retstep=True) # Start # end (HEre end is included) and default elements are 

(array([ 0.        ,  0.51020408,  1.02040816,  1.53061224,  2.04081633,
         2.55102041,  3.06122449,  3.57142857,  4.08163265,  4.59183673,
         5.10204082,  5.6122449 ,  6.12244898,  6.63265306,  7.14285714,
         7.65306122,  8.16326531,  8.67346939,  9.18367347,  9.69387755,
        10.20408163, 10.71428571, 11.2244898 , 11.73469388, 12.24489796,
        12.75510204, 13.26530612, 13.7755102 , 14.28571429, 14.79591837,
        15.30612245, 15.81632653, 16.32653061, 16.83673469, 17.34693878,
        17.85714286, 18.36734694, 18.87755102, 19.3877551 , 19.89795918,
        20.40816327, 20.91836735, 21.42857143, 21.93877551, 22.44897959,
        22.95918367, 23.46938776, 23.97959184, 24.48979592, 25.        ]),
 0.5102040816326531)

In [120]:
np.linspace(0,200,10) # default retstep = False

array([  0.        ,  22.22222222,  44.44444444,  66.66666667,
        88.88888889, 111.11111111, 133.33333333, 155.55555556,
       177.77777778, 200.        ])

In [122]:
np.linspace(0,200,10,retstep=True)

(array([  0.        ,  22.22222222,  44.44444444,  66.66666667,
         88.88888889, 111.11111111, 133.33333333, 155.55555556,
        177.77777778, 200.        ]),
 22.22222222222222)

### Eye
#### Creates an indentity matrix

In [125]:
np.eye(5) # generates 2nd array of (5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [127]:
# Cretae an eye from a zeros array

### Broadcasting in an array

In [132]:
big_one=np.ones((3,4))
print(big_one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [134]:
big_one.dtype

dtype('float64')

In [136]:
big_one *3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

### The ability to access each and every elements of an array is known as Broadcasting

In [139]:
bigger_one = big_one*6-2
bigger_one

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [141]:
bigger = np.array(big_one*3-0.4, dtype='int')
print(bigger)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [143]:
bigger.dtype

dtype('int32')

In [145]:
type(bigger)

numpy.ndarray

In [147]:
bigger.shape

(3, 4)

In [149]:
bigger/bigger

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [151]:
arr1 =np.arange(20)

In [153]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [155]:
arr1 + arr1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [157]:
arr1 ** arr1

array([          1,           1,           4,          27,         256,
              3125,       46656,      823543,    16777216,   387420489,
        1410065408,  1843829075,  -251658240, -1692154371, -1282129920,
        1500973039,           0,  1681328401,   457441280,  -306639989])

## USE of Copy function

In [160]:
arr2 = arr1
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [162]:
arr2[:10]= 30 # using indexing/slicing to modify arr2
arr2

array([30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [164]:
arr1

array([30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [166]:
arr3 = arr1.copy() # generate a copy / creates a backup


In [168]:
arr3[10:] = 100
arr3

array([ 30,  30,  30,  30,  30,  30,  30,  30,  30,  30, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100])

In [170]:
arr1 # copy function retains the original. copy creates a backup array.

array([30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

## Random NUmber Generation
### Numpy also has lots of ways to creates random number arrys.
## rand
#### Creates an array of the given shape and populate it with random samples from a uniform distribution over [0,1]

In [173]:
import numpy as np

In [175]:
np.random.rand()

0.12545459367245337

In [177]:
np.random.rand(10) # rand gives values between 0 adn 1

array([0.6758671 , 0.3824108 , 0.31183028, 0.92180646, 0.58326048,
       0.93553956, 0.34117541, 0.58076487, 0.769164  , 0.22607344])

In [179]:
np.random.rand(10).reshape((2,5))

array([[0.48225375, 0.77479093, 0.21069123, 0.52376821, 0.56135219],
       [0.82925856, 0.17210657, 0.93751228, 0.50779812, 0.99822409]])

In [181]:
# creating array from uniform distribution 
new_arr = np.random.rand(5,3)


In [183]:
new_arr

array([[0.77695442, 0.12557069, 0.88881544],
       [0.6970087 , 0.95037002, 0.18182281],
       [0.9583233 , 0.4021074 , 0.60253477],
       [0.22395227, 0.14679998, 0.18607585],
       [0.04050059, 0.38576818, 0.39344415]])

In [185]:
np.random.rand(3,3)

array([[0.60367789, 0.97720425, 0.45510756],
       [0.14222043, 0.02927201, 0.36693424],
       [0.8936441 , 0.70610948, 0.846438  ]])

### randn
#### Return a sample (or samples) from the "standard normal" distribution. Unlike/ rand when uniform

In [ ]:
# For randn, random numbbers generated will be in approximately -3 to +3 range.

In [190]:
arr1 =np.random.random(50) # 50 observations from std normal distribution
arr1

array([0.27142991, 0.2209646 , 0.37674477, 0.87234773, 0.10110017,
       0.33872499, 0.79854209, 0.6388239 , 0.74167135, 0.87574302,
       0.53747739, 0.85653746, 0.54253432, 0.76345501, 0.41519984,
       0.9237995 , 0.2676119 , 0.05709866, 0.64305606, 0.99493914,
       0.31679947, 0.3114712 , 0.60928475, 0.75892073, 0.00796287,
       0.86559235, 0.54253562, 0.81837681, 0.79578118, 0.73993547,
       0.0725518 , 0.25189084, 0.28793718, 0.83027891, 0.76944249,
       0.13222843, 0.02817643, 0.82792274, 0.5189253 , 0.70900956,
       0.80011428, 0.21359201, 0.38530228, 0.05960907, 0.04977646,
       0.56691768, 0.57412482, 0.83743258, 0.33707706, 0.42201562])

In [192]:
max(arr1)

0.994939137809265

In [194]:
min(arr1)

0.007962872621734562

In [196]:
np.random.randn(3,3)

array([[-0.18858098, -1.03466377,  0.03133868],
       [ 0.39276937,  0.83165137, -0.4642823 ],
       [-1.10445464,  0.04506071, -1.00665051]])

#### randint
##### REturn random integers from low (inclusive) to high (exclusive)

np.random.randint(1,100)

In [201]:
np.random.randint(1,100,10)

array([40, 48, 81, 74, 63, 63, 10, 40, 62, 33])

In [203]:
np.random.randint(40,60,50)

array([40, 57, 47, 44, 55, 50, 46, 58, 45, 47, 47, 49, 57, 59, 54, 48, 51,
       40, 42, 48, 55, 46, 55, 48, 52, 46, 56, 51, 40, 45, 52, 47, 47, 56,
       40, 55, 50, 47, 58, 42, 43, 40, 44, 42, 46, 53, 42, 55, 56, 58])

## Array Attributes and methods
### Let's discuss some useful attributes and methods or an array:

In [210]:
arr = np.arange(20)
ranarr = np.random.randint(0,100,10)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [212]:
ranarr

array([21, 27, 56, 44, 14, 88, 79, 20, 12, 74])

### max, min, argmax, argmin
#### These are useful methods for finding max or min values. Or to find their index locations argmin or argmax

In [215]:
ranarr

array([21, 27, 56, 44, 14, 88, 79, 20, 12, 74])

In [217]:
ranarr.max() # highest elemenet of the array

88

In [219]:
arr.max()

19

In [221]:
ranarr.argmax() # index location of highest element

5

In [223]:
ranarr.min() # Gives the lowest element of array

12

In [225]:
ranarr.argmin() # Index location of lowest element

8

In [227]:
ran2.argmax()

NameError: name 'ran2' is not defined

In [229]:
ran2.max()

NameError: name 'ran2' is not defined