### NumPy Indexing and Selection


In [2]:
import numpy as np

In [4]:
arr = np.arange(0,21)

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

### Bracket Indexing and Selection
#### The simplest way to pick one or some elements of an array looks very similar to python

In [9]:
arr = np.arange(10,100,5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [11]:
len(arr)

18

In [13]:
arr[-1]

95

In [15]:
# get a value at an index
arr[9]

55

In [17]:
# get value in  a range
arr[1:11:2]

array([15, 25, 35, 45, 55])

### Filtering

In [20]:
import numpy as np

In [22]:
# filtering condition
arr = np.array([1,2,1010,4,108,18,71,610])
arr

array([   1,    2, 1010,    4,  108,   18,   71,  610])

In [24]:
arr<100

array([ True,  True, False,  True, False,  True,  True, False])

In [26]:
arr[5]

18

In [28]:
np.where(arr>100) # where function outputs index location of values 
# meeting the condition

(array([2, 4, 7], dtype=int64),)

In [30]:
np.where(arr<100)

(array([0, 1, 3, 5, 6], dtype=int64),)

In [32]:
np.where(arr==100)

(array([], dtype=int64),)

### Indexing a 2D array (matrices)
#### The general format is arr_2d[row][col] or arr_2d[row,col]. It is recommended to use the comma notation for clarity.

In [35]:
import numpy as np

In [37]:
arr_2d = np.array(([1,2,3],[12,15,18],[64,96,128]))
arr_2d

array([[  1,   2,   3],
       [ 12,  15,  18],
       [ 64,  96, 128]])

In [39]:
arr_2d[1:,:2]

array([[12, 15],
       [64, 96]])

In [41]:
arr_2d[2,:2]

array([64, 96])

In [43]:
arr_2d[:,2]

array([  3,  18, 128])

In [47]:
arr_2d[:1,0:3]

array([[1, 2, 3]])

In [49]:
arr_2d.shape

(3, 3)

In [51]:
arr_2d[1]

array([12, 15, 18])

In [53]:
arr_2d[:,2]# Indexing 3rd column

array([  3,  18, 128])

In [55]:
arr_2d[1:,1:]

array([[ 15,  18],
       [ 96, 128]])

In [57]:
arr_2d[0:2]

array([[ 1,  2,  3],
       [12, 15, 18]])

In [59]:
# indexing column
arr_2d[:,2]

array([  3,  18, 128])

In [61]:
# 2D array slicing 
# shape (2,2) from top right corner
arr_2d[:2,1:]

array([[ 2,  3],
       [15, 18]])

### Fancy Indexing 
#### Fancy indexeing allows you to select entire rows or columns out of order, to show this, uickly build out a numpy array:

In [64]:
arr1 = np.ones((10,10))
arr1.shape

(10, 10)

In [66]:
# set up matrix 
arr2d = np.zeros(arr1.shape) # taking shape from an existing array

In [68]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [70]:
arr2d.shape

(10, 10)

In [72]:
arr2d[[3,7]]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [74]:
no_of_wors=arr2d.shape[0]

In [76]:
for j in range(11,21):
    print(j)

11
12
13
14
15
16
17
18
19
20


In [80]:
# set up array
arr2d = np.ones((10,10))
no_of_rows=arr2d.shape[0]


j=0
for i in range(no_of_rows):
    arr2d[i] = np.arange(j+1,j+11)
    j+=10
arr2d

array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [ 11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.],
       [ 21.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.],
       [ 31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.],
       [ 41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.,  50.],
       [ 51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.],
       [ 61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.],
       [ 71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.],
       [ 81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,  90.],
       [ 91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99., 100.]])

In [82]:
import numpy as np
a = np.arange(1,101).reshape(10,10)
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [86]:
arr2d[[3,9,7,5]]

array([[ 31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.],
       [ 91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99., 100.],
       [ 71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.],
       [ 51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.]])

## Fancy indexing allows the following


In [89]:
arr2d[[6,3,8]]

array([[61., 62., 63., 64., 65., 66., 67., 68., 69., 70.],
       [31., 32., 33., 34., 35., 36., 37., 38., 39., 40.],
       [81., 82., 83., 84., 85., 86., 87., 88., 89., 90.]])

In [91]:
arr2d[:,[2,4,6,8]]

array([[ 3.,  5.,  7.,  9.],
       [13., 15., 17., 19.],
       [23., 25., 27., 29.],
       [33., 35., 37., 39.],
       [43., 45., 47., 49.],
       [53., 55., 57., 59.],
       [63., 65., 67., 69.],
       [73., 75., 77., 79.],
       [83., 85., 87., 89.],
       [93., 95., 97., 99.]])

In [93]:
# allows in any order 
arr2d[[6,4,2,7]]

array([[61., 62., 63., 64., 65., 66., 67., 68., 69., 70.],
       [41., 42., 43., 44., 45., 46., 47., 48., 49., 50.],
       [21., 22., 23., 24., 25., 26., 27., 28., 29., 30.],
       [71., 72., 73., 74., 75., 76., 77., 78., 79., 80.]])

## Selection
### Let's briefly go over how to use brackets for selection based off of comparison operators

In [96]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [98]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [100]:
arr2d

array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [ 11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.],
       [ 21.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.],
       [ 31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.],
       [ 41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.,  50.],
       [ 51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.],
       [ 61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.],
       [ 71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.],
       [ 81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,  90.],
       [ 91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99., 100.]])

In [102]:
arr2d[:,0]<40

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [104]:
np.where(arr2d[:,]>40)

(array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6,
        6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8,
        8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9], dtype=int64),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1,
        2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3,
        4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64))

In [106]:
arr2d[[4,5,6,7,8,9]]

array([[ 41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.,  50.],
       [ 51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.],
       [ 61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.],
       [ 71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.],
       [ 81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,  90.],
       [ 91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99., 100.]])

In [108]:
arr2d[np.where(arr2d[:,0]>40)]

array([[ 41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.,  50.],
       [ 51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.],
       [ 61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.],
       [ 71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.],
       [ 81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,  90.],
       [ 91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99., 100.]])