In [1]:
import numpy as np

### 4 how to crt 1D Array ?

In [4]:
num = [1,2,3]
num = np.array(num)
print("1d array: ",num)

1d array:  [1 2 3]


### 5 how to crt 2D Array ?

In [7]:
num2 =[[1,2,3],[4,5,6]]
num2 = np.array(num2)
print("\n2d array : \n", num2)


2d array : 
 [[1 2 3]
 [4 5 6]]


### 6 how to crt 3D Array or ND Array ?

In [10]:
num3 =[[[1,2,3],[4,5,6],[7,8,9]]]
num3 = np.array(num3)
print("\n3d array : \n",num3)


3d array : 
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]]


### 7 how to identified datatype for numpy array ?

In [13]:
print("\n data type num 3",num3.dtype)


 data type num 3 int32


### 8 Print 1D array with 5 zeros

In [16]:
arr =np.zeros(5)
print("single array: ",arr)

single array:  [0. 0. 0. 0. 0.]


### 9 print zeros with 2 rows and columns ?

In [19]:
arr2 = np.zeros((2,3))
print("Array with 2 rows adn 3 cols: \n", arr2)

Array with 2 rows adn 3 cols: 
 [[0. 0. 0.]
 [0. 0. 0.]]


### 10 crt arrray with eye() diagonal values ?

In [22]:
arr3 = np.eye(4)
print("diagonal values : \n",arr3)

diagonal values : 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### 11. use of diag() square matrix ?

In [25]:
arr3 = np.diag([1,2,3,4])
print("square matrix \n",arr3)

square matrix 
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


### 12 Print Range Between 1 to 15 and show 4 integers random numbers

In [28]:
rand_arr = np.random.randint(1,15,4)
print("\n random number from 1 to 15 ", rand_arr)


 random number from 1 to 15  [10  6  7  7]


### 13. Describe the example of seed() function ? adn how to use it ? why seed() ?

#### seed() is used in the process of generating the same sequences of random numbers on a constant basis and use the same number at each time when called

In [31]:
# How many ever times we execute the above code, it will get us the same numbers that are picked randomly for the first time
np.random.seed(123)
rand_arr4 = np.random.randint(1,100,20)
print("seed() showing same number only : ", rand_arr4)

seed() showing same number only :  [67 93 99 18 84 58 87 98 97 48 74 33 47 97 26 84 79 37 97 81]


#### 14. Print first position, last position and 2nd and 3rd position

In [34]:
num = np.array([5,15,25,35])
print("first position : ",num[0]) #5
print("third position : ",num[2]) #25

first position :  5
third position :  25


### 15.if we don’t know last number of position how to show it by pragmatically?

In [37]:
num = np.array([5,15,25,35])
print("last indexing done by -1 position : ",num[-1])

last indexing done by -1 position :  35


### 16. create a matrix 3 * 3 with value ranging from 0 to 8

In [40]:
arr = np.arange(0,9).reshape(3,3)
print(arr)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 17. create matrix 2 * 2 with value ranging from 1 to 3

In [43]:
arr = np.arange(0,4).reshape(2,2)
print(arr)

[[0 1]
 [2 3]]


### 18. create matrix 2 * 2 with value ranging from 1 to 4

In [46]:
arr = np.arange(1,5).reshape(2,2)
print(arr)

[[1 2]
 [3 4]]


### 19. print random number from 0 to 1

In [49]:
a = np.random.rand()
print("random number from 0 to 1 ", a)

random number from 0 to 1  0.7379954057320357


### 20. print size of num array

In [52]:
num = np.array([5,15,25,35])
print("\n size \n",num.size) #100


 size 
 4


### 21. create an array of 20 linearly spaced point between 0 to 1

In [55]:
num_line = np.linspace(0,1,20)
print(num_line)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


### 22. Use of sort() function ?

In [58]:
num_arr = np.array([[5,6,2],[9,8,1]])
print("sorting of numpy array : \n",np.sort(num_arr))

sorting of numpy array : 
 [[2 5 6]
 [1 8 9]]


### 23. How to get the positions where elements of two arrays match?

In [61]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

### 24. Create a Numpy array filled with all zeros

In [64]:
a = np.zeros(3, dtype = int) 
print("Matrix a : \n", a) 
  
b = np.zeros([3, 3], dtype = int) 
print("\nMatrix b : \n", b) 

Matrix a : 
 [0 0 0]

Matrix b : 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


### 25. Check whether a Numpy array contains a specified row

In [67]:
arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20]])

# view the array
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [69]:
## tolist(): used to convert the data elements of an array into a list. 
arr.tolist()

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]

In [71]:
## checking whether the given list is present in the above array.
print([1, 2, 3, 4, 5] in arr.tolist())
print([16, 17, 20, 19, 18] in arr.tolist())
print([3, 2, 5, -4, 5] in arr.tolist())
print([11, 12, 13, 14, 15] in arr.tolist())

True
False
False
True


#### 26 Find the number of occurrences of a sequence in a numpy array

In [74]:
arr = np.array([[2,8,9,4],
                    [9,4,9,4],
                    [4,5,9,7],
                    [2,9,4,3]])
output = repr(arr).count("9,4")
print(output)

0


### 27 Write a Numpy program to test elementwise for NaN of a given array

In [79]:
a = np.array([1, 0, np.nan, np.inf])
print("Original array")
print(a)
print("Test element-wise for NaN:")
print(np.isnan(a))

Original array
[ 1.  0. nan inf]
Test element-wise for NaN:
[False False  True False]


### 28 Write a numpy program to test whether none of the elements of a given array is zero 

In [82]:
x = np.array([1,2,3,4])
print("Original array:")
print(x)
print("Test if npne of the elements of the said array is zero:")
print(np.all(x))
x = np.array([0,1,2,3])
print(x)
print("Test if none of the elements of the said array is zero:")
print(np.all(x))

Original array:
[1 2 3 4]
Test if npne of the elements of the said array is zero:
True
[0 1 2 3]
Test if none of the elements of the said array is zero:
False


### 29. Write a Numpy program to convert a list of numerical value into a one-dimension Numpy array.

In [85]:
l = [12.23, 13.32,100,36.32]
print("original list:",l)
a = np.array(l)
print("One-dimensional NumPy array: ",a)

original list: [12.23, 13.32, 100, 36.32]
One-dimensional NumPy array:  [ 12.23  13.32 100.    36.32]


### 30. Write a Numpy to crt a null vector of size 10 and update sixth value 

In [88]:
x = np.zeros(10)
print(x)
print("\n Update sixth value to 11")
x[6] =11
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

 Update sixth value to 11
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


### 31. Write a NumPy program to crt a 5x5 array with random values and find the minimum and maximum values.

In [91]:
x = np.random.random((5,5))
print("Original Array:")
print(x)
xmin, xmax = x.min(), x.max()
print("\n")
print("minimum and maximum values: ")
print(xmin,xmax)

Original Array:
[[0.18249173 0.17545176 0.53155137 0.53182759 0.63440096]
 [0.84943179 0.72445532 0.61102351 0.72244338 0.32295891]
 [0.36178866 0.22826323 0.29371405 0.63097612 0.09210494]
 [0.43370117 0.43086276 0.4936851  0.42583029 0.31226122]
 [0.42635131 0.89338916 0.94416002 0.50183668 0.62395295]]


minimum and maximum values: 
0.09210493994507518 0.9441600182038796


### 32. Write a Numpy program to compute the multiplication of two given matrices Samples matrix: [[1,0],[0,1]],[[1,2],[3,4]]

In [94]:
p  = [[1,0],[0,1]]
q = [[1,2],[3,4]]
print("original matrix:")
print(p)
result1 = np.dot(p,q)
print("\n")
print("Result of the said matrix multiplication:")
print(result1)

original matrix:
[[1, 0], [0, 1]]


Result of the said matrix multiplication:
[[1 2]
 [3 4]]


### 33. Create a two-dimensional array woth the flattened input as a diagonal 

In [99]:
ar1 = np.diagflat([[1,2], [3,4]])
ar1

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

### 34. Write a Numpy program to compute the sum of the diagonal element of a given array

In [102]:
m = np.arange(6).reshape(3,2)
print("Original matrix:")
print(m)

# trace() will return the sum of diagonal elements 
result = np.trace(m)
print("\n")
print("Condition number of the said matrix:")
print(result)

Original matrix:
[[0 1]
 [2 3]
 [4 5]]


Condition number of the said matrix:
3


In [104]:
a =  np.arange(24).reshape((2,2,2,3))
print(a)
print("\n")
np.trace(a)

[[[[ 0  1  2]
   [ 3  4  5]]

  [[ 6  7  8]
   [ 9 10 11]]]


 [[[12 13 14]
   [15 16 17]]

  [[18 19 20]
   [21 22 23]]]]




array([[18, 20, 22],
       [24, 26, 28]])

In [106]:
a = np.arange(8).reshape((2,2,2))
print(a)
print("\n")
np.trace(a)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]




array([6, 8])

### 35. Use of around() function : returns a decimal values rounded to a desired position decimal

In [109]:
arr = np.array([12.202, 90.23120, 123.020, 23.202]) 
print("printing the original array values:",end = " ")  
print(arr)  
print("\n")
print("Array values rounded off to 2 decimal position",np.around(arr, 2))  
print("Array values rounded off to -1 decimal position",np.around(arr, -1))  

printing the original array values: [ 12.202   90.2312 123.02    23.202 ]


Array values rounded off to 2 decimal position [ 12.2   90.23 123.02  23.2 ]
Array values rounded off to -1 decimal position [ 10.  90. 120.  20.]
